# .github/workflows/docker-compile.yml
name: Docker Compile

on:
  push:
    tags:
      - "v*.*.*"

# Sets permissions of the GITHUB_TOKEN to allow releasing
permissions:
  contents: write

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clone and Compile
      run: |
        ./docker_compile.sh
        ls -lR binaries.tgz binaries

    - name: Release binaries
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: binaries.tgz
